import { ThemeProvider } from "next-themes";
import "../styles/global.css";
import Head from "next/head";

function App({ Component, pageProps }) {
  return (
    <ThemeProvider attribute="class">
      <Head>
        <title>유환빈 프로폴리오</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </ThemeProvider>
  );
}

export default App;
