export const expressionData =[
     {
          value:"angry",
          Kvalue:"화난"
     },
     {
          value:"disgust",
          Kvalue:"혐오스러운"
     },
     {
          value:"fear",
          Kvalue:"두려운"
     },
     {
          value:"laugh",
          Kvalue:"웃는"
     },
     {
          value:"neutral",
          Kvalue:"중립적인"
     },
     {
          value:"sad",
          Kvalue:"슬픈"
     },
     {
          value:"surprise",
          Kvalue:"놀라는"
     },
     {
          value:"smile",
          Kvalue:"미소짓는"
     },
     {
          value:"talking",
          Kvalue:"말하는"
     }
]